[fiveg_sa_core]
coldPath = $SPLUNK_DB/fiveg_sa_core/colddb
enableDataIntegrityControl = 0
enableTsidxReduction = 0
homePath = $SPLUNK_DB/fiveg_sa_core/db
maxTotalDataSizeMB = 512000
thawedPath = $SPLUNK_DB/fiveg_sa_core/thaweddb
