[monitor://$SPLUNK_HOME/etc/apps/TA_5g_sa_core/samples/5g_nf_metrics.json]
disabled = false
index = fiveg_sa_core
sourcetype = 5g:nf:metrics

[monitor://$SPLUNK_HOME/etc/apps/TA_5g_sa_core/samples/5g_service_kpi.json]
disabled = false
index = fiveg_sa_core
sourcetype = 5g:service:kpi

[monitor://$SPLUNK_HOME/etc/apps/TA_5g_sa_core/samples/5g_core_alerts.json]
disabled = false
index = fiveg_sa_core
sourcetype = 5g:core:alerts

[monitor://$SPLUNK_HOME/etc/apps/TA_5g_sa_core/samples/5g_subscriber_experience.json]
disabled = false
index = fiveg_sa_core
sourcetype = 5g:subscriber:experience
